import 'package:shopease_ecom_app/data/const/app_assets.dart';
import 'package:shopease_ecom_app/data/helpers/data.dart';
import 'package:shopease_ecom_app/data/helpers/product_category.dart';
import 'package:shopease_ecom_app/data/helpers/product_filter.dart';

class ProductModel {
  String id;
  String image;
  String name;
  double oldPrice;
  double currentPrice;
  String offPercentage;
  int totalRatings;
  double averageRatings;
  String description;
  String ownerName;
  ProductCategory category;
  ProductFilter filter;

  ProductModel({
    required this.id,
    required this.image,
    required this.name,
    required this.oldPrice,
    required this.currentPrice,
    required this.offPercentage,
    required this.totalRatings,
    required this.averageRatings,
    required this.description,
    required this.ownerName,
    required this.category,
    required this.filter,
  });
}

List<ProductModel> dummyProductList = [
  ProductModel(
    id: '1',
    image: AppAssets.kDummyProduct1,
    name: 'Mini  speaker ',
    oldPrice: 99.99,
    currentPrice: 69.99,
    offPercentage: '25% Off',
    totalRatings: 520,
    averageRatings: 4.9,
    description: dummyTextDescription,
    ownerName: 'Michael Brown',
    category: ProductCategory.toys,
    filter: ProductFilter.mostPopular,
  ),
  ProductModel(
    id: '2',
    image: AppAssets.kDummyProduct2,
    name: 'cleaning tool',
    oldPrice: 879.99,
    currentPrice: 549.99,
    offPercentage: '15% Off',
    totalRatings: 850,
    averageRatings: 4.7,
    description: dummyTextDescription,
    ownerName: 'Electro World',
    category: ProductCategory.electronics,
    filter: ProductFilter.latest,
  ),
  ProductModel(
    id: '3',
    image: AppAssets.kDummyProduct3,
    name: 'VR headset',
    oldPrice: 349.99,
    currentPrice: 219.99,
    offPercentage: '20% Off',
    totalRatings: 430,
    averageRatings: 4.8,
    description: dummyTextDescription,
    ownerName: 'Sports Hub',
    category: ProductCategory.electronics,
    filter: ProductFilter.mostPopular,
  ),
  ProductModel(
    id: '4',
    image: AppAssets.kDummyProduct4,
    name: 'Organic Face Cream',
    oldPrice: 49.99,
    currentPrice: 39.99,
    offPercentage: '20% Off',
    totalRatings: 210,
    averageRatings: 4.5,
    description: dummyTextDescription,
    ownerName: 'Beauty Bliss',
    category: ProductCategory.beauty,
    filter: ProductFilter.latest,
  ),
  ProductModel(
    id: '5',
    image: AppAssets.kDummyProduct5,
    name: 'Modern Bookshelf',
    oldPrice: 199.99,
    currentPrice: 159.99,
    offPercentage: '20% Off',
    totalRatings: 290,
    averageRatings: 4.6,
    description: dummyTextDescription,
    ownerName: 'Home Decor',
    category: ProductCategory.furniture,
    filter: ProductFilter.brand,
  ),
  ProductModel(
    id: '6',
    image: AppAssets.kDummyProduct6,
    name: 'Make up Sponges',
    oldPrice: 149.99,
    currentPrice: 99.99,
    offPercentage: '33% Off',
    totalRatings: 180,
    averageRatings: 4.5,
    description: dummyTextDescription,
    ownerName: 'Sophia Davis',
    category: ProductCategory.furniture,
    filter: ProductFilter.brand,
  ),
  ProductModel(
    id: '7',
    image: AppAssets.kDummyProduct7,
    name: 'Modern Dining Table',
    oldPrice: 39.99,
    currentPrice: 29.99,
    offPercentage: '25% Off',
    totalRatings: 85,
    averageRatings: 4.6,
    description: dummyTextDescription,
    ownerName: 'David Clark',
    category: ProductCategory.furniture,
    filter: ProductFilter.mostPopular,
  ),
  ProductModel(
    id: '8',
    image: AppAssets.kDummyProduct8,
    name: 'Compression Packing Cubes for Travel',
    oldPrice: 199.99,
    currentPrice: 149.99,
    offPercentage: '25% Off',
    totalRatings: 210,
    averageRatings: 4.8,
    description: dummyTextDescription,
    ownerName: 'Olivia White',
    category: ProductCategory.furniture,
    filter: ProductFilter.latest,
  ),
  ProductModel(
    id: '9',
    image: AppAssets.kDummyProduct9,
    name: 'Modern Premium Sofa',
    oldPrice: 149.99,
    currentPrice: 119.99,
    offPercentage: '20% Off',
    totalRatings: 174,
    averageRatings: 4.7,
    description: dummyTextDescription,
    ownerName: 'Daniel Lee',
    category: ProductCategory.furniture,
    filter: ProductFilter.mostPopular,
  ),
  ProductModel(
    id: '10',
    image: AppAssets.kDummyProduct10,
    name: 'Rustic Bookshelf',
    oldPrice: 99.99,
    currentPrice: 79.99,
    offPercentage: '20% Off',
    totalRatings: 10,
    averageRatings: 4.6,
    description: dummyTextDescription,
    ownerName: 'Ava Martinez',
    category: ProductCategory.furniture,
    filter: ProductFilter.latest,
  ),
  ProductModel(
    id: '11',
    image: AppAssets.kDummyProduct11,
    name: 'Accent Wooden Chairs',
    oldPrice: 29.99,
    currentPrice: 19.99,
    offPercentage: '33% Off',
    totalRatings: 68,
    averageRatings: 4.5,
    description: dummyTextDescription,
    ownerName: 'James Harris',
    category: ProductCategory.furniture,
    filter: ProductFilter.brand,
  ),
];
